spring.datasource.url=jdbc:mysql://mysql-2d60a4bc-electro001.a.aivencloud.com:13335/defaultdb?useSSL=true&requireSSL=true&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_mfU-WoEdF3_0A_h-HWa
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=electro
# spring.thymeleaf.cache=false
spring.web.resources.cache.period=0